
project_id = "flhdgdpewxooxtxqqhdz"

[api]
# Port to use for the API URL.
port = 54323
schemes = ["http"]
extra_search_paths = ["extensions"]
max_rows = 1000

[db]
# Port to use for the local database URL.
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 15
max_client_conn = 100
acquire_timeout = 600

[studio]
enabled = true
port = 54321
api_url = "http://localhost"

[inbucket]
# The email testing server.
# User-facing URL where the inbucket UI is accessible.
enabled = false
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
# The S3-compatible object storage server.
enabled = true
port = 54327
file_storage_backend = "file"
file_storage_upload_timeout = 30000
# The maximum file size allowed, in bytes.
# Defaults to 50MB.
file_size_limit = "50MiB"

[auth]
# The JWT secret used to sign JWT tokens.
enabled = true

[realtime]
enabled = true
ip_version = "IPv6"

[analytics]
enabled = false

[edge_functions]
enabled = true
port = 54328

[functions.add-product]
verify_jwt = true

[functions.check-products]
verify_jwt = true

[functions.enable-realtime]
verify_jwt = true

[functions.execute-sql]
verify_jwt = true

[functions.update-product]
verify_jwt = true
