// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://flhdgdpewxooxtxqqhdz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZsaGRnZHBld3hvb3h0eHFxaGR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxODc4ODgsImV4cCI6MjA2Mjc2Mzg4OH0.ZDT4JO3QQb1zlaD-NeMT0pcAJ-aNhDELNqyB3Gyl9no";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);